### ISSUE TITLE
Trying to hijack your blog 

### ISSUE THREAD

**Issue by ldicarlo** [Kerollmops/blog#2]
I am sorry I really wanted to know if this would create a page also on your blog.

**Comment by ldicarlo** [comment]
It doesn't because - I guess - of the article labels. 
^^

**Comment by Kerollmops** [comment]
Ahah 😂 I added a part explaining this behavior. I am the only one having the triage role and therefore I am the only one being able to expose posts on my blog by using the _article_ label.

However, if I label this issue correctly, you'll see your issue content on my blog with you profile picture and name 🥳
